# Generated by Django 4.0.4 on 2022-06-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_boost_type_core_auto_click_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boost',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'auto'), (0, 'casual')], default=0),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
