# Generated by Django 4.0.4 on 2022-06-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_achievement_type_alter_boost_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='type',
        ),
        migrations.AlterField(
            model_name='boost',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'auto'), (0, 'casual')], default=0),
        ),
    ]
